### ISSUE TITLE
Launcher icon / logo

### ISSUE THREAD

**Issue by joas8211** [joas8211/ForceDarkModeOreo#1]
If there's any helpful minds, we could use logo to be used as a launcher icon.
No requirements special, it just has to follow the law.

**Comment by moghir2004** [comment]
It can be like some oreo cookie opened in half showing the chocolate  outer side and the inner white cream side (dark vs white)
![image](https://user-images.githubusercontent.com/19752607/42375944-3dc4b4b4-8115-11e8-8356-6f12385f6782.png)
